<?xml version="1.0"?>
<package format="2">
  <name>dofbot_waste_sorting</name>
  <version>0.1.0</version>
  <description>Vision-guided waste sorting pipeline for a Yahboom DOFBOT robotic arm.</description>

  <maintainer email="virgile-tchidehou@users.noreply.github.com">Dodji Virgile TCHIDEHOU</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>cv_bridge</build_depend>
  <build_depend>message_generation</build_depend>

  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>rospkg</exec_depend>
</package>
