training:
  model: yolov5m
  img_size: 640
  epochs: 100
  batch_size: 8
  patience: 25

  lr0: 0.01
  momentum: 0.937
  weight_decay: 0.0005

  data: ../data/dataset.yaml

  project: ../runs
  name: dofbot_waste_sorting
